[build]
  command = "npm run build"

[functions]
  # Configures all functions to include the Prisma engine
  included_files = ["node_modules/.prisma/client/**/*", "node_modules/@prisma/client/**/*", "prisma/**/*"]
  node_bundler = "esbuild"
