[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Configures all functions to include the Prisma engine
  included_files = ["node_modules/.prisma/client/**/*", "node_modules/@prisma/client/**/*", "prisma/**/*"]

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    Clear-Site-Data = "\"cache\""

# Trigger build for OfficeCity - v4




